import { appConfig } from "@/app/config/env";
import type { Brand } from "@/types/brand";

const API_BASE = appConfig.apiUrl.replace(/\/api\/?$/, "");

const FALLBACK_BRANDS: Brand[] = [
  {
    id: "brand-001",
    name: "NexPhone Labs",
    slug: "nexphone-labs",
    code: "NX",
    logoIcon: "sparkles",
    accentColor: "#6366f1",
    description: "Pioneering next-generation quantum-accelerated smartphones with aerospace-grade zero-trust hardware enclaves.",
    country: "United States",
    headquarters: "San Francisco, CA",
    foundedYear: 2021,
    website: "https://nexphone.io",
    supportEmail: "concierge@nexphone.io",
    status: "active",
    tier: "Flagship",
    isFeatured: true,
    deviceCount: 8,
    marketShare: "42.5%",
    rating: 4.9,
    createdAt: "2026-09-01T00:00:00.000Z",
    updatedAt: "2026-10-01T00:00:00.000Z",
  },
  {
    id: "brand-002",
    name: "BlackMesa Telecom",
    slug: "blackmesa-telecom",
    code: "BM",
    logoIcon: "shield",
    accentColor: "#06b6d4",
    description: "High-security tactical communicators engineered for defense fleets, remote research, and extreme telemetry.",
    country: "United States",
    headquarters: "Seattle, WA",
    foundedYear: 2018,
    website: "https://blackmesa.io",
    supportEmail: "ops@blackmesa.io",
    status: "active",
    tier: "Enterprise",
    isFeatured: true,
    deviceCount: 6,
    marketShare: "24.1%",
    rating: 4.8,
    createdAt: "2026-09-02T00:00:00.000Z",
    updatedAt: "2026-10-02T00:00:00.000Z",
  },
  {
    id: "brand-003",
    name: "Weyland Mobile",
    slug: "weyland-mobile",
    code: "WM",
    logoIcon: "globe",
    accentColor: "#10b981",
    description: "Global satellite communications and zero-latency interplanetary VoIP mesh networking architectures.",
    country: "United Kingdom",
    headquarters: "London, UK",
    foundedYear: 2019,
    website: "https://weyland-mobile.co.uk",
    supportEmail: "fleet@weyland-mobile.com",
    status: "active",
    tier: "Strategic",
    isFeatured: true,
    deviceCount: 5,
    marketShare: "15.3%",
    rating: 4.7,
    createdAt: "2026-09-03T00:00:00.000Z",
    updatedAt: "2026-10-02T00:00:00.000Z",
  },
  {
    id: "brand-004",
    name: "Tyrell Secure",
    slug: "tyrell-secure",
    code: "TS",
    logoIcon: "cpu",
    accentColor: "#ec4899",
    description: "Biometric and neural-assisted security chips with autonomous silicon-level intrusion containment.",
    country: "Japan",
    headquarters: "Tokyo, JP",
    foundedYear: 2020,
    website: "https://tyrellsecure.jp",
    supportEmail: "support@tyrellsecure.jp",
    status: "active",
    tier: "OEM Partner",
    isFeatured: true,
    deviceCount: 4,
    marketShare: "9.8%",
    rating: 4.6,
    createdAt: "2026-09-04T00:00:00.000Z",
    updatedAt: "2026-10-01T00:00:00.000Z",
  },
  {
    id: "brand-005",
    name: "Cyberdyne Comms",
    slug: "cyberdyne-comms",
    code: "CC",
    logoIcon: "zap",
    accentColor: "#f59e0b",
    description: "Autonomous self-healing mesh nodes and hardened military handheld communication consoles.",
    country: "Germany",
    headquarters: "Berlin, DE",
    foundedYear: 2017,
    website: "https://cyberdyne-comms.de",
    supportEmail: "contact@cyberdyne-comms.de",
    status: "active",
    tier: "Strategic",
    isFeatured: false,
    deviceCount: 3,
    marketShare: "5.2%",
    rating: 4.5,
    createdAt: "2026-09-05T00:00:00.000Z",
    updatedAt: "2026-09-30T00:00:00.000Z",
  },
  {
    id: "brand-006",
    name: "Massive Dynamic",
    slug: "massive-dynamic",
    code: "MD",
    logoIcon: "gem",
    accentColor: "#8b5cf6",
    description: "Experimental materials lab engineering ultra-dense titanium-ceramic composites and sapphire shields.",
    country: "Sweden",
    headquarters: "Stockholm, SE",
    foundedYear: 2022,
    website: "https://massivedynamic.se",
    supportEmail: "enterprise@massivedynamic.se",
    status: "active",
    tier: "Flagship",
    isFeatured: true,
    deviceCount: 4,
    marketShare: "3.1%",
    rating: 4.8,
    createdAt: "2026-09-06T00:00:00.000Z",
    updatedAt: "2026-10-03T00:00:00.000Z",
  },
];

export const brandService = {
  async getBrands(): Promise<Brand[]> {
    try {
      const res = await fetch(`${API_BASE}/api/brands`, {
        cache: "no-store",
      });
      if (!res.ok) throw new Error("Failed to fetch brands");
      const data = await res.json();
      return Array.isArray(data) && data.length > 0 ? data : FALLBACK_BRANDS;
    } catch {
      return FALLBACK_BRANDS;
    }
  },
};
