import type {
  Customer,
  CustomerSummaryMetrics,
  CustomerFilterParams,
  ToggleCustomerStatusPayload,
} from "@/types/customer";
import { appConfig } from "@/config/env";

const FALLBACK_CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    customerNumber: "CUST-8021",
    name: "Alex Vance",
    email: "a.vance@blackmesa.io",
    phone: "+1 (206) 555-0194",
    company: "Black Mesa Aerospace",
    status: "active",
    tier: "VIP",
    address: {
      street: "742 Evergreen Terrace",
      city: "Seattle",
      state: "WA",
      postalCode: "98101",
      country: "United States",
    },
    metrics: {
      totalOrders: 4,
      totalSpent: 4218.42,
      avgOrderValue: 1054.6,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
      lastLoginIp: "198.51.100.42 (Seattle, US)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9042",
        orderNumber: "NX-ORD-9042",
        createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
        totalAmount: 1409.42,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 1,
      },
      {
        id: "NX-ORD-8812",
        orderNumber: "NX-ORD-8812",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
        totalAmount: 1299.0,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 1,
      },
      {
        id: "NX-ORD-8409",
        orderNumber: "NX-ORD-8409",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
        totalAmount: 1510.0,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 2,
      },
    ],
    notes: "Executive partner at Black Mesa. Eligible for priority express courier dispatch.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "cust-002",
    customerNumber: "CUST-8022",
    name: "Sophia Tanaka",
    email: "s.tanaka@cyberdyne.co.jp",
    phone: "+81 3-5555-0182",
    company: "Cyberdyne Systems Tokyo",
    status: "active",
    tier: "Enterprise",
    address: {
      street: "Minato-ku, Roppongi Hills Mori Tower 28F",
      city: "Tokyo",
      state: "Tokyo",
      postalCode: "106-6108",
      country: "Japan",
    },
    metrics: {
      totalOrders: 3,
      totalSpent: 3897.0,
      avgOrderValue: 1299.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      lastLoginIp: "203.0.113.88 (Tokyo, JP)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9041",
        orderNumber: "NX-ORD-9041",
        createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        totalAmount: 1299.0,
        status: "processing",
        paymentStatus: "paid",
        itemCount: 1,
      },
      {
        id: "NX-ORD-8701",
        orderNumber: "NX-ORD-8701",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
        totalAmount: 2598.0,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 2,
      },
    ],
    notes: "Requires DHL Global Express priority tracking with commercial duty documentation.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 120).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "cust-003",
    customerNumber: "CUST-8023",
    name: "Marcus Sterling",
    email: "m.sterling@acmeholdings.com",
    phone: "+44 20 7946 0912",
    company: "Acme Holdings Ltd",
    status: "active",
    tier: "Enterprise",
    address: {
      street: "124 Bishopsgate, Level 14",
      city: "London",
      state: "Greater London",
      postalCode: "EC2N 4BQ",
      country: "United Kingdom",
    },
    metrics: {
      totalOrders: 2,
      totalSpent: 2825.82,
      avgOrderValue: 1412.91,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: false,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 100).toISOString(),
      lastLoginIp: "195.55.80.12 (London, UK)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9040",
        orderNumber: "NX-ORD-9040",
        createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        totalAmount: 2825.82,
        status: "shipped",
        paymentStatus: "paid",
        itemCount: 2,
      },
    ],
    notes: "Fleet expansion account. Considers 50+ enterprise rollouts in Q4.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "cust-004",
    customerNumber: "CUST-8024",
    name: "Elena Rostova",
    email: "e.rostova@berlin-tech.de",
    phone: "+49 30 1234567",
    company: "Berlin Tech Labs GmbH",
    status: "active",
    tier: "Pro",
    address: {
      street: "Friedrichstraße 42",
      city: "Berlin",
      state: "Berlin",
      postalCode: "10117",
      country: "Germany",
    },
    metrics: {
      totalOrders: 3,
      totalSpent: 3097.0,
      avgOrderValue: 1032.33,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: false,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
      lastLoginIp: "91.198.174.192 (Berlin, DE)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9039",
        orderNumber: "NX-ORD-9039",
        createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
        totalAmount: 1199.0,
        status: "pending",
        paymentStatus: "pending",
        itemCount: 1,
      },
      {
        id: "NX-ORD-8622",
        orderNumber: "NX-ORD-8622",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
        totalAmount: 1898.0,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 2,
      },
    ],
    notes: "Requires EU VAT compliance receipts.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "cust-005",
    customerNumber: "CUST-8025",
    name: "David Chen",
    email: "d.chen@apexvoip.sg",
    phone: "+65 6789 0123",
    company: "Apex Telecom Singapore",
    status: "active",
    tier: "VIP",
    address: {
      street: "8 Marina Boulevard, Marina Bay Financial Centre",
      city: "Singapore",
      state: "Central",
      postalCode: "018981",
      country: "Singapore",
    },
    metrics: {
      totalOrders: 5,
      totalSpent: 6495.0,
      avgOrderValue: 1299.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
      lastLoginIp: "202.166.192.10 (Singapore, SG)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9038",
        orderNumber: "NX-ORD-9038",
        createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
        totalAmount: 1299.0,
        status: "confirmed",
        paymentStatus: "paid",
        itemCount: 1,
      },
    ],
    notes: "VIP corporate partner. Commercial invoices sent directly to accounts@apexvoip.sg.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 240).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
  },
  {
    id: "cust-006",
    customerNumber: "CUST-8026",
    name: "Sarah Connor",
    email: "s.connor@skyfleet.org",
    phone: "+1 (512) 555-8391",
    company: "SkyFleet Security Systems",
    status: "active",
    tier: "Regular",
    address: {
      street: "1000 Congress Avenue, Suite 400",
      city: "Austin",
      state: "TX",
      postalCode: "78701",
      country: "United States",
    },
    metrics: {
      totalOrders: 1,
      totalSpent: 1299.0,
      avgOrderValue: 1299.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: false,
      twoFactorEnabled: false,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
      lastLoginIp: "104.28.19.44 (Austin, US)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9037",
        orderNumber: "NX-ORD-9037",
        createdAt: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
        totalAmount: 1299.0,
        status: "cancelled",
        paymentStatus: "refunded",
        itemCount: 1,
      },
    ],
    notes: "Customer cancelled first order due to unexpected travel schedule; invited to reorder.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 700).toISOString(),
  },
  {
    id: "cust-007",
    customerNumber: "CUST-8027",
    name: "Liam O'Connor",
    email: "l.oconnor@dublin-comm.ie",
    phone: "+353 1 496 0192",
    company: "Celtic Communications",
    status: "active",
    tier: "Pro",
    address: {
      street: "Grand Canal Quay, Docklands",
      city: "Dublin",
      state: "Leinster",
      postalCode: "D02 Y890",
      country: "Ireland",
    },
    metrics: {
      totalOrders: 2,
      totalSpent: 2198.0,
      avgOrderValue: 1099.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      lastLoginIp: "89.101.240.11 (Dublin, IE)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9036",
        orderNumber: "NX-ORD-9036",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
        totalAmount: 1099.0,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 1,
      },
    ],
    notes: "Hardware developer testing NexPhone custom firmware builds.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "cust-008",
    customerNumber: "CUST-8028",
    name: "Victor Vance",
    email: "v.vance@vice-logistics.com",
    phone: "+1 (305) 555-0149",
    company: "Vice Logistics Inc",
    status: "disabled",
    tier: "Regular",
    address: {
      street: "1400 Ocean Drive, Suite 801",
      city: "Miami",
      state: "FL",
      postalCode: "33139",
      country: "United States",
    },
    metrics: {
      totalOrders: 1,
      totalSpent: 0,
      avgOrderValue: 0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    security: {
      emailVerified: false,
      phoneVerified: false,
      twoFactorEnabled: false,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
      lastLoginIp: "198.51.100.99 (Miami, US)",
    },
    recentOrders: [],
    notes: "Account suspended due to 5 consecutive failed card authorizations and mismatched billing address.",
    disabledReason: "Suspected card testing / fraudulent transaction activity",
    disabledAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    disabledBy: "Compliance & Security Bot",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "cust-009",
    customerNumber: "CUST-8029",
    name: "Amara Okafor",
    email: "a.okafor@lagos-fintech.ng",
    phone: "+234 1 234 5678",
    company: "Lagos FinTech Systems",
    status: "active",
    tier: "VIP",
    address: {
      street: "14 Admiralty Way, Lekki Phase 1",
      city: "Lagos",
      state: "Lagos State",
      postalCode: "105102",
      country: "Nigeria",
    },
    metrics: {
      totalOrders: 4,
      totalSpent: 4896.0,
      avgOrderValue: 1224.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      lastLoginIp: "102.89.23.11 (Lagos, NG)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9035",
        orderNumber: "NX-ORD-9035",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
        totalAmount: 1299.0,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 1,
      },
    ],
    notes: "Preferred partner in West Africa region. High-volume purchaser.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 95).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: "cust-010",
    customerNumber: "CUST-8030",
    name: "Hiroshi Sato",
    email: "h.sato@kyoto-robotics.jp",
    phone: "+81 75 555 0199",
    company: "Kyoto Robotics R&D",
    status: "active",
    tier: "Enterprise",
    address: {
      street: "Shimogyo-ku, Karasuma-dori 12",
      city: "Kyoto",
      state: "Kyoto",
      postalCode: "600-8216",
      country: "Japan",
    },
    metrics: {
      totalOrders: 3,
      totalSpent: 3697.0,
      avgOrderValue: 1232.33,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      lastLoginIp: "133.242.18.90 (Kyoto, JP)",
    },
    recentOrders: [
      {
        id: "NX-ORD-9034",
        orderNumber: "NX-ORD-9034",
        createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
        totalAmount: 1199.0,
        status: "delivered",
        paymentStatus: "paid",
        itemCount: 1,
      },
    ],
    notes: "Conducts hardware stress-testing on robotics automated docks.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 80).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
  {
    id: "cust-011",
    customerNumber: "CUST-8031",
    name: "Chloe Dubois",
    email: "c.dubois@paris-telecom.fr",
    phone: "+33 1 42 68 55 00",
    company: "Hexagone Telecom Paris",
    status: "active",
    tier: "Pro",
    address: {
      street: "28 Boulevard Haussmann",
      city: "Paris",
      state: "Île-de-France",
      postalCode: "75009",
      country: "France",
    },
    metrics: {
      totalOrders: 2,
      totalSpent: 2398.0,
      avgOrderValue: 1199.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: false,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      lastLoginIp: "195.154.120.4 (Paris, FR)",
    },
    recentOrders: [],
    notes: "Requires French localized compliance and CE test documentation.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: "cust-012",
    customerNumber: "CUST-8032",
    name: "Carlos Mendez",
    email: "c.mendez@sol-technologies.mx",
    phone: "+52 55 5123 4567",
    company: "Sol Technologies CDMX",
    status: "active",
    tier: "Regular",
    address: {
      street: "Paseo de la Reforma 222",
      city: "Mexico City",
      state: "CDMX",
      postalCode: "06600",
      country: "Mexico",
    },
    metrics: {
      totalOrders: 1,
      totalSpent: 1199.0,
      avgOrderValue: 1199.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: false,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
      lastLoginIp: "187.189.44.12 (CDMX, MX)",
    },
    recentOrders: [],
    notes: "LATAM trial user for dual-eSIM enterprise deployment.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: "cust-013",
    customerNumber: "CUST-8033",
    name: "Astrid Lindgren",
    email: "a.lindgren@nordic-cellular.se",
    phone: "+46 8 123 4567",
    company: "Nordic Cellular Networks",
    status: "active",
    tier: "VIP",
    address: {
      street: "Kungsgatan 44",
      city: "Stockholm",
      state: "Stockholm",
      postalCode: "111 35",
      country: "Sweden",
    },
    metrics: {
      totalOrders: 5,
      totalSpent: 5795.0,
      avgOrderValue: 1159.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
      lastLoginIp: "85.224.90.15 (Stockholm, SE)",
    },
    recentOrders: [],
    notes: "Top Nordic partner. Fast-track logistics via DHL Express Arlanda hub.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 200).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: "cust-014",
    customerNumber: "CUST-8034",
    name: "Tariq Al-Mansoor",
    email: "t.almansoor@dubai-cloud.ae",
    phone: "+971 4 362 7000",
    company: "Dubai Cloud Horizons",
    status: "active",
    tier: "Enterprise",
    address: {
      street: "DIFC Gate Building, Level 8",
      city: "Dubai",
      state: "Dubai",
      postalCode: "506500",
      country: "United Arab Emirates",
    },
    metrics: {
      totalOrders: 3,
      totalSpent: 3897.0,
      avgOrderValue: 1299.0,
      lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    },
    security: {
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: true,
      lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
      lastLoginIp: "94.200.12.88 (Dubai, AE)",
    },
    recentOrders: [],
    notes: "Regional enterprise procurement account.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 110).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
];

// Supplementary customers to provide 50 realistic records (exactly 10 pages at 5 items/page)
const ADDITIONAL_CUSTOMERS: Customer[] = [
  {
    id: "cust-015",
    customerNumber: "CUST-8035",
    name: "Kavita Rao",
    email: "k.rao@bangalore-robotics.in",
    phone: "+91 80 4123 4567",
    company: "Bangalore Robotics Corp",
    status: "active",
    tier: "Enterprise",
    address: { street: "100 Feet Rd, Indiranagar", city: "Bangalore", state: "Karnataka", postalCode: "560038", country: "India" },
    metrics: { totalOrders: 5, totalSpent: 6490.0, avgOrderValue: 1298.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(), lastLoginIp: "103.21.124.50 (Bangalore, IN)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 160).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "cust-016",
    customerNumber: "CUST-8036",
    name: "Lucas Meyer",
    email: "l.meyer@zurich-quant.ch",
    phone: "+41 44 211 4455",
    company: "Zurich Quant Systems",
    status: "active",
    tier: "VIP",
    address: { street: "Bahnhofstrasse 45", city: "Zurich", state: "Zurich", postalCode: "8001", country: "Switzerland" },
    metrics: { totalOrders: 7, totalSpent: 9240.0, avgOrderValue: 1320.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(), lastLoginIp: "193.134.25.10 (Zurich, CH)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 210).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "cust-017",
    customerNumber: "CUST-8037",
    name: "Camila Santos",
    email: "c.santos@saopaulo-media.br",
    phone: "+55 11 98765-4321",
    company: "Santos Digital Media",
    status: "active",
    tier: "Pro",
    address: { street: "Av. Paulista 1000, 12º andar", city: "São Paulo", state: "SP", postalCode: "01310-100", country: "Brazil" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString() },
    security: { emailVerified: true, phoneVerified: false, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(), lastLoginIp: "177.18.200.4 (São Paulo, BR)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 95).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "cust-018",
    customerNumber: "CUST-8038",
    name: "Hassan Al-Mansoor",
    email: "hassan@doha-ventures.qa",
    phone: "+974 4455 6677",
    company: "Al-Mansoor Tech Holdings",
    status: "active",
    tier: "VIP",
    address: { street: "West Bay Commercial Tower 19", city: "Doha", state: "Doha", postalCode: "24411", country: "Qatar" },
    metrics: { totalOrders: 6, totalSpent: 8790.0, avgOrderValue: 1465.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), lastLoginIp: "82.148.96.12 (Doha, QA)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 180).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "cust-019",
    customerNumber: "CUST-8039",
    name: "Astrid Lindholm",
    email: "astrid.l@stockholm-design.se",
    phone: "+46 8 123 4567",
    company: "Nordic Clean Tech AB",
    status: "active",
    tier: "Pro",
    address: { street: "Sveavägen 44", city: "Stockholm", state: "Stockholm", postalCode: "111 34", country: "Sweden" },
    metrics: { totalOrders: 2, totalSpent: 1798.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(), lastLoginIp: "194.236.10.8 (Stockholm, SE)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 80).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: "cust-020",
    customerNumber: "CUST-8040",
    name: "Mateo Rossi",
    email: "m.rossi@milano-telecom.it",
    phone: "+39 02 8765 4321",
    company: "Rossi Mobili SpA",
    status: "active",
    tier: "Enterprise",
    address: { street: "Via Montenapoleone 8", city: "Milan", state: "Lombardy", postalCode: "20121", country: "Italy" },
    metrics: { totalOrders: 4, totalSpent: 5196.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(), lastLoginIp: "151.15.44.89 (Milan, IT)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 140).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "cust-021",
    customerNumber: "CUST-8041",
    name: "Nadia Petrova",
    email: "n.petrova@vienna-logic.at",
    phone: "+43 1 512 3456",
    company: "Petrova Dynamics GmbH",
    status: "disabled",
    tier: "Regular",
    address: { street: "Kärntner Ring 12", city: "Vienna", state: "Vienna", postalCode: "1010", country: "Austria" },
    metrics: { totalOrders: 1, totalSpent: 599.0, avgOrderValue: 599.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 40).toISOString() },
    security: { emailVerified: true, phoneVerified: false, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(), lastLoginIp: "193.170.80.2 (Vienna, AT)" },
    disabledReason: "Suspected credit card dispute chargeback",
    disabledAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
    disabledBy: "Compliance Team",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 35).toISOString(),
  },
  {
    id: "cust-022",
    customerNumber: "CUST-8042",
    name: "Ethan Wright",
    email: "e.wright@austin-chip.com",
    phone: "+1 (512) 555-0143",
    company: "Wright Semiconductor",
    status: "active",
    tier: "VIP",
    address: { street: "500 W 2nd St, Suite 1900", city: "Austin", state: "TX", postalCode: "78701", country: "United States" },
    metrics: { totalOrders: 8, totalSpent: 11450.0, avgOrderValue: 1431.25, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(), lastLoginIp: "136.56.24.11 (Austin, US)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 300).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "cust-023",
    customerNumber: "CUST-8043",
    name: "Mei-Ling Zhou",
    email: "zhou.ml@taipei-photonics.tw",
    phone: "+886 2 2345 6789",
    company: "Taipei Photonics Ltd",
    status: "active",
    tier: "Enterprise",
    address: { street: "Xinyi Rd Sec 5, No 7", city: "Taipei", state: "Taipei", postalCode: "110", country: "Taiwan" },
    metrics: { totalOrders: 5, totalSpent: 6890.0, avgOrderValue: 1378.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(), lastLoginIp: "140.112.30.9 (Taipei, TW)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 170).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "cust-024",
    customerNumber: "CUST-8044",
    name: "Sebastian Becker",
    email: "s.becker@munich-auto.de",
    phone: "+49 89 987654",
    company: "Bavaria Auto Systems",
    status: "active",
    tier: "Pro",
    address: { street: "Leopoldstraße 110", city: "Munich", state: "Bavaria", postalCode: "80802", country: "Germany" },
    metrics: { totalOrders: 3, totalSpent: 2997.0, avgOrderValue: 999.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), lastLoginIp: "188.192.40.15 (Munich, DE)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 115).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
  },
  {
    id: "cust-025",
    customerNumber: "CUST-8045",
    name: "Chloe Dubois",
    email: "c.dubois@lyon-biotech.fr",
    phone: "+33 4 72 00 11 22",
    company: "Lyon Biotech Research",
    status: "active",
    tier: "Pro",
    address: { street: "Rue de la République 18", city: "Lyon", state: "Rhône", postalCode: "69002", country: "France" },
    metrics: { totalOrders: 2, totalSpent: 1898.0, avgOrderValue: 949.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), lastLoginIp: "90.84.120.3 (Lyon, FR)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 85).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
  },
  {
    id: "cust-026",
    customerNumber: "CUST-8046",
    name: "Kenji Sato",
    email: "k.sato@osaka-optics.jp",
    phone: "+81 6 6123 4567",
    company: "Kansai Optics Corp",
    status: "active",
    tier: "Enterprise",
    address: { street: "Umeda 1-1-3, Kita-ku", city: "Osaka", state: "Osaka", postalCode: "530-0001", country: "Japan" },
    metrics: { totalOrders: 4, totalSpent: 5196.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(), lastLoginIp: "133.242.18.99 (Osaka, JP)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 130).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
  },
  {
    id: "cust-027",
    customerNumber: "CUST-8047",
    name: "Amara Okonjo",
    email: "a.okonjo@lagos-fintech.ng",
    phone: "+234 1 234 5678",
    company: "West Africa Digital Pay",
    status: "active",
    tier: "Regular",
    address: { street: "Adetokunbo Ademola St", city: "Lagos", state: "Lagos", postalCode: "101241", country: "Nigeria" },
    metrics: { totalOrders: 2, totalSpent: 1198.0, avgOrderValue: 599.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(), lastLoginIp: "105.112.45.6 (Lagos, NG)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 70).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
  },
  {
    id: "cust-028",
    customerNumber: "CUST-8048",
    name: "Viktor Novak",
    email: "v.novak@prague-cyber.cz",
    phone: "+420 221 456 789",
    company: "Bohemia Cyber Security",
    status: "active",
    tier: "Pro",
    address: { street: "Wenceslas Square 22", city: "Prague", state: "Prague", postalCode: "110 00", country: "Czech Republic" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(), lastLoginIp: "195.113.80.12 (Prague, CZ)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 100).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
  },
  {
    id: "cust-029",
    customerNumber: "CUST-8049",
    name: "Zara Chen",
    email: "zara.chen@melbourne-health.au",
    phone: "+61 3 9876 5432",
    company: "Southern Cross Health Tech",
    status: "active",
    tier: "VIP",
    address: { street: "Collins Street 101", city: "Melbourne", state: "VIC", postalCode: "3000", country: "Australia" },
    metrics: { totalOrders: 6, totalSpent: 7794.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(), lastLoginIp: "139.130.4.5 (Melbourne, AU)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 240).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "cust-030",
    customerNumber: "CUST-8050",
    name: "Dmitri Volkov",
    email: "d.volkov@helsinki-cloud.fi",
    phone: "+358 9 1234 5678",
    company: "Nordic Aurora Cloud",
    status: "disabled",
    tier: "Regular",
    address: { street: "Mannerheimintie 14", city: "Helsinki", state: "Uusimaa", postalCode: "00100", country: "Finland" },
    metrics: { totalOrders: 1, totalSpent: 499.0, avgOrderValue: 499.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 50).toISOString() },
    security: { emailVerified: true, phoneVerified: false, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(), lastLoginIp: "193.166.4.1 (Helsinki, FI)" },
    disabledReason: "Inactive account flagged by automated security audit",
    disabledAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
    disabledBy: "System Guard",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    id: "cust-031",
    customerNumber: "CUST-8051",
    name: "Priya Sharma",
    email: "priya@mumbai-fin.in",
    phone: "+91 22 2654 3210",
    company: "Maharashtra Capital Advisory",
    status: "active",
    tier: "Pro",
    address: { street: "BKC Complex, Bandra East", city: "Mumbai", state: "Maharashtra", postalCode: "400051", country: "India" },
    metrics: { totalOrders: 4, totalSpent: 3596.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(), lastLoginIp: "115.114.80.20 (Mumbai, IN)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 125).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: "cust-032",
    customerNumber: "CUST-8052",
    name: "Gabriel Garcia",
    email: "g.garcia@madrid-energy.es",
    phone: "+34 91 555 4321",
    company: "Iberia Solar & Energy",
    status: "active",
    tier: "Enterprise",
    address: { street: "Paseo de la Castellana 200", city: "Madrid", state: "Madrid", postalCode: "28046", country: "Spain" },
    metrics: { totalOrders: 5, totalSpent: 6495.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(), lastLoginIp: "88.2.140.55 (Madrid, ES)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 155).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "cust-033",
    customerNumber: "CUST-8053",
    name: "Ananya Patel",
    email: "ananya.p@singapore-data.sg",
    phone: "+65 6789 0123",
    company: "Lion City Data Systems",
    status: "active",
    tier: "VIP",
    address: { street: "Marina Boulevard 8A", city: "Singapore", state: "Central", postalCode: "018981", country: "Singapore" },
    metrics: { totalOrders: 7, totalSpent: 9793.0, avgOrderValue: 1399.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(), lastLoginIp: "202.166.4.12 (Singapore, SG)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 220).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "cust-034",
    customerNumber: "CUST-8054",
    name: "Liam O'Connor",
    email: "l.oconnor@dublin-pay.ie",
    phone: "+353 1 496 0123",
    company: "Emerald Isle Cloud Labs",
    status: "active",
    tier: "Pro",
    address: { street: "Grand Canal Square 2", city: "Dublin", state: "Leinster", postalCode: "D02 A342", country: "Ireland" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 32).toISOString(), lastLoginIp: "89.101.40.18 (Dublin, IE)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 11).toISOString(),
  },
  {
    id: "cust-035",
    customerNumber: "CUST-8055",
    name: "Fatima Zahra",
    email: "f.zahra@casablanca-tech.ma",
    phone: "+212 522 123 456",
    company: "Atlas Telecommunications",
    status: "active",
    tier: "Regular",
    address: { street: "Boulevard d'Anfa 88", city: "Casablanca", state: "Grand Casablanca", postalCode: "20000", country: "Morocco" },
    metrics: { totalOrders: 2, totalSpent: 1198.0, avgOrderValue: 599.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 80).toISOString(), lastLoginIp: "196.200.4.15 (Casablanca, MA)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 65).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22).toISOString(),
  },
  {
    id: "cust-036",
    customerNumber: "CUST-8056",
    name: "Noah Takahashi",
    email: "noah.t@kyoto-craft.jp",
    phone: "+81 75 345 6789",
    company: "Kyoto Robotics Studio",
    status: "active",
    tier: "Enterprise",
    address: { street: "Shijo Karasuma 12", city: "Kyoto", state: "Kyoto", postalCode: "600-8009", country: "Japan" },
    metrics: { totalOrders: 4, totalSpent: 5196.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 15).toISOString(), lastLoginIp: "118.238.10.88 (Kyoto, JP)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 145).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "cust-037",
    customerNumber: "CUST-8057",
    name: "Isabella Rossi",
    email: "i.rossi@florence-design.it",
    phone: "+39 055 234 5678",
    company: "Firenze Luxury Tech",
    status: "active",
    tier: "Pro",
    address: { street: "Piazza della Signoria 5", city: "Florence", state: "Tuscany", postalCode: "50122", country: "Italy" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 13).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(), lastLoginIp: "93.45.12.80 (Florence, IT)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 105).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 13).toISOString(),
  },
  {
    id: "cust-038",
    customerNumber: "CUST-8058",
    name: "Benjamin Hughes",
    email: "b.hughes@toronto-ai.ca",
    phone: "+1 (416) 555-0188",
    company: "Great Lakes Neural Network",
    status: "active",
    tier: "VIP",
    address: { street: "100 King St W, Suite 4000", city: "Toronto", state: "ON", postalCode: "M5X 1A9", country: "Canada" },
    metrics: { totalOrders: 6, totalSpent: 8394.0, avgOrderValue: 1399.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(), lastLoginIp: "142.214.10.4 (Toronto, CA)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 230).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "cust-039",
    customerNumber: "CUST-8059",
    name: "Sora Hayashi",
    email: "s.hayashi@sapporo-sensor.jp",
    phone: "+81 11 234 5678",
    company: "Hokkaido Thermal Systems",
    status: "active",
    tier: "Regular",
    address: { street: "Odori Nishi 4-chome", city: "Sapporo", state: "Hokkaido", postalCode: "060-0042", country: "Japan" },
    metrics: { totalOrders: 2, totalSpent: 1198.0, avgOrderValue: 599.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 95).toISOString(), lastLoginIp: "219.100.8.12 (Sapporo, JP)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 75).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
  },
  {
    id: "cust-040",
    customerNumber: "CUST-8060",
    name: "Oliver Smith",
    email: "oliver.s@manchester-iot.co.uk",
    phone: "+44 161 234 5678",
    company: "Pennine Industrial IoT",
    status: "active",
    tier: "Pro",
    address: { street: "Peter House, Oxford St", city: "Manchester", state: "Greater Manchester", postalCode: "M1 5AN", country: "United Kingdom" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(), lastLoginIp: "82.44.18.90 (Manchester, UK)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 110).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
  },
  {
    id: "cust-041",
    customerNumber: "CUST-8061",
    name: "Emma Watson",
    email: "e.watson@oxford-genomics.org",
    phone: "+44 1865 270000",
    company: "Oxford BioCompute",
    status: "active",
    tier: "Enterprise",
    address: { street: "Parks Road 14", city: "Oxford", state: "Oxfordshire", postalCode: "OX1 3PJ", country: "United Kingdom" },
    metrics: { totalOrders: 5, totalSpent: 6495.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(), lastLoginIp: "129.67.1.5 (Oxford, UK)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 165).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "cust-042",
    customerNumber: "CUST-8062",
    name: "Lucas Silva",
    email: "lucas.s@lisbon-startups.pt",
    phone: "+351 21 345 6789",
    company: "Tejo Silicon Valley",
    status: "active",
    tier: "Pro",
    address: { street: "Avenida da Liberdade 180", city: "Lisbon", state: "Lisbon", postalCode: "1250-146", country: "Portugal" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString() },
    security: { emailVerified: true, phoneVerified: false, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(), lastLoginIp: "193.136.2.8 (Lisbon, PT)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 95).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
  {
    id: "cust-043",
    customerNumber: "CUST-8063",
    name: "Mia Zhang",
    email: "mia.zhang@auckland-tele.co.nz",
    phone: "+64 9 379 1234",
    company: "Aotearoa Cloud Connect",
    status: "active",
    tier: "VIP",
    address: { street: "Queen Street 205", city: "Auckland", state: "Auckland", postalCode: "1010", country: "New Zealand" },
    metrics: { totalOrders: 6, totalSpent: 8394.0, avgOrderValue: 1399.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 80).toISOString(), lastLoginIp: "210.55.12.8 (Auckland, NZ)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 250).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "cust-044",
    customerNumber: "CUST-8064",
    name: "Alexander Müller",
    email: "a.mueller@frankfurt-fin.de",
    phone: "+49 69 7654 3210",
    company: "Main River Financial",
    status: "active",
    tier: "Enterprise",
    address: { street: "Taunusanlage 8", city: "Frankfurt", state: "Hesse", postalCode: "60329", country: "Germany" },
    metrics: { totalOrders: 5, totalSpent: 6495.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(), lastLoginIp: "194.138.1.10 (Frankfurt, DE)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 175).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "cust-045",
    customerNumber: "CUST-8065",
    name: "Aria Montgomery",
    email: "aria.m@vancouver-clean.ca",
    phone: "+1 (604) 555-0177",
    company: "Pacific Hydrogen Dynamics",
    status: "active",
    tier: "Pro",
    address: { street: "Burrard St 1055, Suite 2100", city: "Vancouver", state: "BC", postalCode: "V6E 3P3", country: "Canada" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 16).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 55).toISOString(), lastLoginIp: "199.116.115.1 (Vancouver, CA)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 115).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 16).toISOString(),
  },
  {
    id: "cust-046",
    customerNumber: "CUST-8066",
    name: "Leo Hernandez",
    email: "leo.h@bogota-fintech.co",
    phone: "+57 1 234 5678",
    company: "Andes Digital Banking",
    status: "active",
    tier: "Regular",
    address: { street: "Carrera 7 No 71-21", city: "Bogotá", state: "Cundinamarca", postalCode: "110221", country: "Colombia" },
    metrics: { totalOrders: 2, totalSpent: 1198.0, avgOrderValue: 599.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 110).toISOString(), lastLoginIp: "186.28.40.12 (Bogotá, CO)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 80).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 28).toISOString(),
  },
  {
    id: "cust-047",
    customerNumber: "CUST-8067",
    name: "Zoe Kravitz",
    email: "zoe.k@amsterdam-creative.nl",
    phone: "+31 20 123 4567",
    company: "Keizersgracht Media Lab",
    status: "active",
    tier: "Pro",
    address: { street: "Keizersgracht 421", city: "Amsterdam", state: "North Holland", postalCode: "1016 EK", country: "Netherlands" },
    metrics: { totalOrders: 4, totalSpent: 3596.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(), lastLoginIp: "145.100.2.14 (Amsterdam, NL)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 135).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: "cust-048",
    customerNumber: "CUST-8068",
    name: "Julian Brandt",
    email: "j.brandt@copenhagen-green.dk",
    phone: "+45 33 12 34 56",
    company: "Ørsted Green Logistics",
    status: "active",
    tier: "Enterprise",
    address: { street: "Kongens Nytorv 8", city: "Copenhagen", state: "Capital Region", postalCode: "1050", country: "Denmark" },
    metrics: { totalOrders: 5, totalSpent: 6495.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 13).toISOString(), lastLoginIp: "192.38.10.2 (Copenhagen, DK)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 160).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "cust-049",
    customerNumber: "CUST-8069",
    name: "Hannah Abbott",
    email: "h.abbott@edinburgh-biotech.ac.uk",
    phone: "+44 131 650 1000",
    company: "Lothian BioLabs",
    status: "active",
    tier: "Pro",
    address: { street: "George Square 18", city: "Edinburgh", state: "Midlothian", postalCode: "EH8 9JZ", country: "United Kingdom" },
    metrics: { totalOrders: 3, totalSpent: 2697.0, avgOrderValue: 899.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 17).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: false, lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(), lastLoginIp: "129.215.10.8 (Edinburgh, UK)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 100).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 17).toISOString(),
  },
  {
    id: "cust-050",
    customerNumber: "CUST-8070",
    name: "Finnian MacLeod",
    email: "f.macleod@belfast-photon.co.uk",
    phone: "+44 28 9097 5555",
    company: "Antrim Quantum Sensors",
    status: "active",
    tier: "VIP",
    address: { street: "Titanic Quarter, Queen's Rd", city: "Belfast", state: "Antrim", postalCode: "BT3 9DT", country: "United Kingdom" },
    metrics: { totalOrders: 7, totalSpent: 9093.0, avgOrderValue: 1299.0, lastOrderDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString() },
    security: { emailVerified: true, phoneVerified: true, twoFactorEnabled: true, lastLoginAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(), lastLoginIp: "143.117.1.4 (Belfast, UK)" },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 260).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
];

// In-memory working cache populated with all 50 customer records
let localCustomers: Customer[] = [...FALLBACK_CUSTOMERS, ...ADDITIONAL_CUSTOMERS];

export const CustomerService = {
  /**
   * Fetch all customers with query filtering, status, and tier filters.
   */
  async getCustomers(params: CustomerFilterParams = {}): Promise<Customer[]> {
    const { search = "", status = "all", tier = "all", sortBy = "recent" } = params;

    try {
      const url = new URL(`${appConfig.apiUrl}/api/customers`);
      if (search) url.searchParams.set("search", search);
      if (status !== "all") url.searchParams.set("status", status);
      if (tier !== "all") url.searchParams.set("tier", tier);
      if (sortBy) url.searchParams.set("sortBy", sortBy);

      const res = await fetch(url.toString(), {
        headers: { Accept: "application/json" },
        cache: "no-store",
      });

      if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
      const data = await res.json();
      localCustomers = data;
      return data;
    } catch {
      // Robust offline fallback filter
      let filtered = [...localCustomers];

      if (search.trim()) {
        const q = search.toLowerCase();
        filtered = filtered.filter(
          (c) =>
            c.name.toLowerCase().includes(q) ||
            c.email.toLowerCase().includes(q) ||
            c.phone.toLowerCase().includes(q) ||
            c.customerNumber.toLowerCase().includes(q) ||
            c.address.city.toLowerCase().includes(q) ||
            c.address.country.toLowerCase().includes(q) ||
            (c.company && c.company.toLowerCase().includes(q))
        );
      }

      if (status !== "all") {
        filtered = filtered.filter((c) => c.status === status);
      }

      if (tier !== "all") {
        filtered = filtered.filter((c) => c.tier === tier);
      }

      if (sortBy === "spent_desc") {
        filtered.sort((a, b) => b.metrics.totalSpent - a.metrics.totalSpent);
      } else if (sortBy === "orders_desc") {
        filtered.sort((a, b) => b.metrics.totalOrders - a.metrics.totalOrders);
      } else if (sortBy === "name_asc") {
        filtered.sort((a, b) => a.name.localeCompare(b.name));
      } else {
        filtered.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
      }

      return filtered;
    }
  },

  /**
   * Fetch single customer details by ID or CustomerNumber
   */
  async getCustomerById(id: string): Promise<Customer | null> {
    try {
      const res = await fetch(`${appConfig.apiUrl}/api/customers/${encodeURIComponent(id)}`, {
        headers: { Accept: "application/json" },
        cache: "no-store",
      });
      if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
      return await res.json();
    } catch {
      const found = localCustomers.find((c) => c.id === id || c.customerNumber === id);
      return found ?? null;
    }
  },

  /**
   * Toggle account status (Enable / Disable)
   */
  async toggleStatus(payload: ToggleCustomerStatusPayload): Promise<Customer> {
    const { customerId, status, reason, note, performedBy = "Admin Staff" } = payload;

    try {
      const res = await fetch(`${appConfig.apiUrl}/api/customers/${encodeURIComponent(customerId)}/status`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status, reason, note, performedBy }),
      });
      if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
      const updated = await res.json();

      const idx = localCustomers.findIndex((c) => c.id === customerId || c.customerNumber === customerId);
      if (idx !== -1) {
        localCustomers[idx] = updated;
      }
      return updated;
    } catch {
      const idx = localCustomers.findIndex((c) => c.id === customerId || c.customerNumber === customerId);
      const current = localCustomers[idx];
      if (idx === -1 || !current) throw new Error("Customer not found in local store");

      const now = new Date().toISOString();

      const updated: Customer = {
        ...current,
        status,
        disabledReason: status === "disabled" ? reason || "Administrative restriction" : undefined,
        disabledAt: status === "disabled" ? now : undefined,
        disabledBy: status === "disabled" ? performedBy : undefined,
        notes: note
          ? `${current.notes ? `${current.notes}\n` : ""}[${new Date().toLocaleDateString()}] ${performedBy}: ${note}`
          : current.notes,
        updatedAt: now,
      };

      localCustomers[idx] = updated;
      return updated;
    }
  },

  /**
   * Get high-level customer telemetry metrics
   */
  async getMetrics(): Promise<CustomerSummaryMetrics> {
    try {
      const res = await fetch(`${appConfig.apiUrl}/api/customers-metrics`, {
        headers: { Accept: "application/json" },
        cache: "no-store",
      });
      if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
      return await res.json();
    } catch {
      const totalCustomers = localCustomers.length;
      const activeCustomers = localCustomers.filter((c) => c.status === "active").length;
      const disabledCustomers = localCustomers.filter((c) => c.status === "disabled").length;
      const totalLtv = localCustomers.reduce((acc, c) => acc + c.metrics.totalSpent, 0);
      const avgSpendPerCustomer = totalCustomers > 0 ? totalLtv / totalCustomers : 0;
      const vipCustomers = localCustomers.filter((c) => c.tier === "VIP" || c.tier === "Enterprise").length;

      return {
        totalCustomers,
        activeCustomers,
        disabledCustomers,
        totalLtv,
        avgSpendPerCustomer,
        vipCustomers,
      };
    }
  },
};
